version: 0.0
os: linux
files:
- source: /
  destination: /var/www/html
overwrite: true  
hooks:
  BeforeInstall:
    - location: remove.sh
  AfterInstall:
    - location: permissions.sh
      timeout: 120